---
- name: Ensure the latest list of packages are installed
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - httpd
      - httpd-tools
      - php

- name: Deploy apache config file
  ansible.builtin.template:
    src: files/server-status.conf
    dest: /etc/httpd/conf.d/server-status.conf
    mode: "0644"

- name: Deploy php document to DocumentRoot
  ansible.builtin.template:
    src: files/info.php
    dest: /var/www/html/info.php
    mode: "0644"

- name: Deploy html document to DocumentRoot
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"

- name: Ensure apache is running
  ansible.builtin.service:
    name: httpd
    state: restarted
