---
- name: Ensure the latest list of packages are installed
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - httpd
      - httpd-tools
      - php

- name: Ensure web files are populated from templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.path }}"
    mode: "0644"
  loop:
    - src: "{{ role_path }}/templates/index.html.j2"
      path: /var/www/html/index.html
    - src: "{{ role_path }}/templates/main.js.j2"
      path: /var/www/html/js/main.js
    - src: "{{ role_path }}/templates/main.css.j2"
      path: /var/www/html/css/main.css
    - src: "{{ role_path }}/templates/info.php.j2"
      path: /var/www/html/info.php
    - src: "{{ role_path }}/templates/server-status.conf.j2"
      path: /etc/httpd/conf.d/server-status.conf 

- name: Ensure apache is running
  ansible.builtin.service:
    name: httpd
    state: restarted
