version: 0.2

env:
  variables:
    TEMPLATE_URL: "https://wanna-cf-aaf-wtf-us-west-2.s3.us-west-2.amazonaws.com/artifacts/compute.aws.yml"
    AWS_REGION: "us-west-2"
    TAG_ENVIRONMENT: "wtf-aaf"
    TAG_NAME: "wanna-cf_compute"
    TAG_GROUP: "wanna-cf_webservers"
    MAX_SIZE: "2"
    MIN_SIZE: "1"
    VOLUME_SIZE: "150"
    DESIRED_CAPACITY: "1"
    LOAD_BALANCER_TARGET_DRAIN: "60"

  parameter-store:
    INSTANCE_TYPE: "/wanna-cf/aaf/instance_type"
    SSH_LOCATION: "/wanna-cf/aaf/ssh_location"
    KEY_NAME: "/wanna-cf/aaf/key_name"
    DNS_NAME: "/wanna-cf/aaf/dns_name"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -q
  build:
    commands:
      - codebuild-breakpoint
      - make deploy ENV=wtf PLAY=compute REGION=us-west-2 EVARS="prefix=wanna"
