version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -q
  build:
    commands:
      - cd ansible
      - ansible-playbook -i inventories/ playbooks/40_integration_tests.yml -e stack_prefix="brent-cf"
  post_build:
    commands:
      - ansible-playbook -i inventories/ playbooks/roles/integration_tests/tests/test.yml -e stack_prefix="brent-cf"
