version: 0.2

env:
  variables:
    TEMPLATE_URL: "https://tester-cf-aaf-wtf-us-west-2.s3.us-west-2.amazonaws.com/artifacts/network.aws.yml"
    ENDPOINTS_TEMPLATE_URL: "https://tester-cf-aaf-wtf-us-west-2.s3.us-west-2.amazonaws.com/artifacts/endpoints.aws.yml"
    AWS_REGION: "us-west-2"
    TAG_ENVIRONMENT: "aaf"
  parameter-store:
    VPC_CIDR: "/tester-cf/aaf/vpc_cidr"
    PUBLIC_SUBNET_1_CIDR: "/tester-cf/aaf/public_subnet_1_cidr"
    PUBLIC_SUBNET_2_CIDR: "/tester-cf/aaf/public_subnet_2_cidr"
    PRIVATE_SUBNET_1_CIDR: "/tester-cf/aaf/private_subnet_1_cidr"
    PRIVATE_SUBNET_2_CIDR: "/tester-cf/aaf/private_subnet_2_cidr"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -q
  build:
    commands:
      - make deploy ENV=wtf PLAY=network REGION=us-west-2 EVARS="prefix=tester"
  post_build:
    commands:
      - cd ansible
      - ansible-playbook playbooks/roles/network/tests/test.yml -e stack_prefix=tester-cf
