version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt -q
      - cfn-lint -v
  build:
    commands:
      - sh buildspec/lint-cfn-templates.sh
artifacts:
  files:
    - '**/*'
  base-directory: cloudformation
  discard-paths: yes
