version: 0.2

env:
  parameter-store:
    ANSIBLE_PRIVATE_KEY: "/tetris-cf/aaf/ansible_private_key"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - dnf install -y python3-pip
      - pip install -r requirements.txt -q
      - mkdir -p ~/.ssh
      - echo "$ANSIBLE_PRIVATE_KEY" > ~/.ssh/ansible
      - chmod 600 ~/.ssh/ansible
  pre_build:
    commands:
      - eval $(ssh-agent)
      - ssh-add ~/.ssh/ansible
      - cd ansible
      - ansible-inventory -i inventory/ --graph
      - codebuild-breakpoint
      - ansible-playbook -i inventory/ playbooks/roles/compute/tests/test.yml -e test_hosts="tetris_cf"
  build:
    commands:
      - ansible-playbook -i inventory/ playbooks/30_web_config.yml -e hosts="tetris_cf"
  post_build:
    commands:
      - ansible-playbook -i inventory/ playbooks/roles/httpd/tests/test.yml -e test_hosts="tetris_cf"

