---
- name: Set stack_name fact
  ansible.builtin.set_fact:
    stack_name: "{{ stack_prefix }}-network"

- name: Create network resources
  amazon.aws.cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ aws_region }}"
    template_url: "{{ lookup('env', 'TEMPLATE_URL') }}"
    create_changeset: "{{ create_changeset }}"
    template_parameters:
      VpcCIDR: "{{ lookup('env', 'VPC_CIDR') }}"
      PublicSubnet1CIDR: "{{ lookup('env', 'PUBLIC_SUBNET_1_CIDR') }}"
      PublicSubnet2CIDR: "{{ lookup('env', 'PUBLIC_SUBNET_2_CIDR') }}"
      PrivateSubnet1CIDR: "{{ lookup('env', 'PRIVATE_SUBNET_1_CIDR') }}"
      PrivateSubnet2CIDR: "{{ lookup('env', 'PRIVATE_SUBNET_2_CIDR') }}"
      TagEnv: "{{ aws_profile }}"
    tags:
      stack: "{{ stack_name }}"

- name: Get network facts
  amazon.aws.cloudformation_info:
    stack_name: "{{ stack_name }}"
  register: stack_facts

- name: Set network fact
  ansible.builtin.set_fact:
    network_facts: "{{ stack_facts['cloudformation'][stack_name].stack_outputs }}"

- name: Create VPC endpoint resources
  amazon.aws.cloudformation:
    stack_name: "{{ stack_prefix }}-endpoints"
    state: present
    region: "{{ aws_region }}"
    template_url: "{{ lookup('env', 'ENDPOINTS_TEMPLATE_URL') }}"
    create_changeset: "{{ create_changeset }}"
    template_parameters:
      RouteTables: "{{ network_facts.PrivateRouteTables }}"
      Subnets: "{{ network_facts.PrivateSubnets }}"
      VpcId: "{{ network_facts.VpcId }}"
    tags:
      stack: "{{ stack_name }}"
