Description: Codepipeline

Parameters:
  CodePipelineServiceRoleArn:
    Default: $iam-CodePipelineServiceRoleArn
    Description: The ARN of the CodePipeline service role
    Type: String

  S3ArtifactLocation:
    Description: The name of the S3 bucket to store artifacts
    Type: String

  RepositoryName:
    Description: The name of the CodeCommit repository
    Type: String

  StackPrefix:
    Description: The prefix for stack resources
    Type: String

Conditions:
  CodePipelineServiceRoleIsImported:
    !And [
      !Not [ !Equals [ !Ref CodePipelineServiceRoleArn, ""] ],
      !Equals [ !Select [ 0, !Split [ "$", !Ref CodePipelineServiceRoleArn ] ], ""]
    ]

Resources:
  CodePipelinePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${AWS::StackName}-pipeline"
      RoleArn: 
        !If 
          - CodePipelineServiceRoleIsImported
          - Fn::ImportValue:
              !Join [ "-", [ !Sub "${StackPrefix}", !Select [ 1, !Split [ "$", !Ref CodePipelineServiceRoleArn ] ] ] ]
          - !Join [ "-", [ !Sub "${StackPrefix}", !Ref CodePipelineServiceRoleArn ] ]
      ArtifactStore:
        Location: !Ref S3ArtifactLocation
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                BranchName: main
                OutputArtifactFormat: CODEBUILD_CLONE_REF
                PollForSourceChanges: "false"
                RepositoryName: !Ref RepositoryName
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref AWS::Region
              Namespace: SourceVariables
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: cfn-validate
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Region: !Ref AWS::Region
              Namespace: BuildVariables
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: "1"
              Configuration:
                BucketName: !Ref S3ArtifactLocation
                Extract: "true"
                ObjectKey: templates
              InputArtifacts:
                - Name: BuildArtifact
              Region: !Ref AWS::Region
              RunOrder: 1
