Description: Iam resources

Resources:
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action: 'lambda:*'
                Effect: 'Allow'
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
          PolicyName: LambdaFullAccessPolicy
      RoleName: !Sub "${AWS::StackName}-ApiGatewayRole"

  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: "/service-role/"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "ec2:*"
                  - "cloudformation:*"
                  - "ssm:*"
                  - "elasticloadbalancing:*"
                  - "iam:*"
                  - "autoscaling:*"
                  - "elaslasticLoadBalancingV2:*"
                  - "route53:*"
                  - "s3:*"
                  - "codecommit:*"
                  - "codebuild:*"
                  - "logs:*"
                Effect: "Allow"
                Resource: "*"
          PolicyName: CodeBuildBasePolicy
      RoleName: !Sub "${AWS::StackName}-CodeBuildServiceRole"

  CodePipelineServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/service-role/"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'iam:PassRole'
                Resource: '*'
                Condition:
                  StringEqualsIfExists:
                    'iam:PassedToService':
                      - cloudformation.amazonaws.com
                      - elasticbeanstalk.amazonaws.com
                      - ec2.amazonaws.com
                      - ecs-tasks.amazonaws.com
              - Effect: Allow
                Action:
                  - "codecommit:*"
                  - "codedeploy:*"
                  - "codestar-connections:UseConnection"
                  - "lambda:InvokeFunction"
                  - "lambda:ListFunctions"
                  - "elasticbeanstalk:*"
                  - "ec2:*"
                  - "elasticloadbalancing:*"
                  - "autoscaling:*"
                  - "cloudwatch:*"
                  - "s3:*"
                  - "sns:*"
                  - "cloudformation:*"
                  - "rds:*"
                  - "ssm:GetParameters"
                  - "sqs:*"
                  - "s3:*"
                  - "codebuild:*"
                  - "logs:*"
                Resource: "*"
          PolicyName: CodeBuildBasePolicy
      RoleName: !Sub "${AWS::StackName}-CodePipelineServiceRole"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Path: '/'
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
          PolicyName: LambdaLogPolicy
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "dynamodb:*"
                Effect: "Allow"
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
          PolicyName: LambdaDynamoDbPolicy
      RoleName: !Sub "${AWS::StackName}-LambdaRole"

Outputs:
  ApiGatewayRoleArn:
    Description: The ARN of the ApiGateway Role
    Value: !GetAtt ApiGatewayRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayRoleArn"

  CodeBuildServiceRoleArn:
    Description: The ARN of the CodeBuildService Role
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildServiceRoleArn"

  CodePipelineServiceRoleArn:
    Description: The ARN of the CodePipelineService Role
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CodePipelineServiceRoleArn"

  LambdaRoleArn:
    Description: The ARN of the Lambda Role
    Value: !GetAtt LambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaRoleArn"
